apiVersion: apps/v1
kind: Service
metadata:
  name: reactapp-service
  labels:
    app: reactapp-project
  spec:
    selector:
      app: reactapp-project
    type: NodePort
    ports:
     -port: 3000
      targetPort: 3000
      nodePort: 30180