apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
  spec:
   selector:
    matchLabels:
      app: reactapp-project
  template:
    metadata:
      labels:
        app: reactapp-project
    spec:
      containers:
      - name: reactapp-project
        image: ramu215/reactapp
        ports:
        - containerPort: 3000